---
title: "Korea_demo"
author: "coop711"
date: '2017 9 29 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data

[인구, 가구 및 주택 - 시군구](http://kosis.kr/statisticsList/statisticsList_01List.jsp?vwcd=MT_ZTITLE&parentId=A)

```{r, kosis data}
options(width = 180)
library(tidyverse)
library(extrafont) #> "HCR Dotum LVT" 사용하기 위한 조치
census_data <- read.csv("../data/101_DT_1IN1502_Y_2015.csv",
                        header = TRUE, #> 한글 변수명 그대로 읽어들일 예정
                        na.strings = "X",  #> 통계청 데이터에서 NA는 "X"로 표시되어 있음.
                        skip = 2,
                        stringsAsFactors = FALSE,
                        # encoding = "CP949") Invaild multibyte string Error
                        fileEncoding = "euc-kr") #> `encoding = "CP949"` 과의 차이 숙지.
str(census_data) #> 지역 code 와 이름 외에는 모두 숫자로 읽어들임.
census_data[1:100, 1:6]
```

## Data Cleaning

### 변수명

```{r, names}
names(census_data) #> 변수명에 "..", "."를 "_"로 바꿔 주어야 함.
# gsub("\\.$", "", names(census_data))
# names_census <- gsub("\\.$", "", names(census_data))
# gsub("\\.+", "_", names_census)
# names(census_data) <- gsub("\\.+", "_", names_census)
# names(census_data)
#> piping 으로 흘러가면, data holder "." 을 활용하여
# names(census_data) <- names(census_data) %>%
# {gsub("\\.$", "", .)} %>%
# {gsub("\\.+", "_", .)}
#> {}는 없어도 무방
names(census_data) <- names(census_data) %>% 
  gsub("\\.$", "", .) %>% 
  gsub("\\.+", "_", .)
names(census_data) #> 바뀐 변수명 확인
```

### 지역명 코드 앞 자리 특수기호와 지역명 앞 빈 공간

```{r, code}
census_data %>%
  .[, 1] %>%
  head()
# head(census_data$C행정구역별_읍면동) #> code 앞 자리에 "`" 제거 필요
census_data$C행정구역별_읍면동 <- census_data$C행정구역별_읍면동 %>%
  sub("^\\'", "", .)
# head(census_data$C행정구역별_읍면동) #> 처리 결과 확인
census_data %>%
  .[, 1] %>%
  head()
census_data %>%  #> 읍면동 명 앞에 빈 공간 존재 확인
  .[, 2] %>%
  head(10)
census_data$행정구역별_읍면동 <- census_data$행정구역별_읍면동 %>%
  gsub("^\\s+", "", .)
census_data %>%  #> 읍면동 명 앞에 빈 공간 존재 확인
  .[, 2] %>%
  head(20)
```

```{r}
census_data[, 1:6]
```

## 시도 데이터

```{r, filter sido}
census_data[1:10, 1:6] #> 다음 "%>%"를 이용하는 방법들은 모두 동일한 결과
census_data %>%
  "["(., 1:10, 1:6) 
census_data %>%
  `[`(., 1:10, ) %>%
  select(C행정구역별_읍면동:여자_명)
census_data %>%
  slice(1:10) %>%
  select(C행정구역별_읍면동:여자_명)
census_data %>%
  .[1:10, 1:6]
census_data %>% #> 세종특별자치시의 득수성, 광역으로 분류되면서 시군구에도 동시 분류
  filter({
    census_data %>%  #> `{}`의 용법에 유의.
#   select(C행정구역별_읍면동) %>% #> 작동하지 않음. list 추출
      .[, 1] %>%  #> 작동함. atomic vector cncnf
      substr(1, 2) %>% 
      `==`("29")}) %>%
  select(C행정구역별_읍면동:여자_명)
#> piping 을 최소화하면,
# census_data %>%
#   filter(substr(census_data$C행정구역별_읍면동, 1, 2) == "29") %>%
#   select(C행정구역별_읍면동:여자_명)
data_sido <- census_data %>%  #> 시도 코드는 두 자리이고 11(서울)부터 매겨짐. 00은 전체, 03은 동, 04는 읍, 05는 면부의 총계임. 
#  filter(nchar(C행정구역별_읍면동) == 2 & 
#           C행정구역별_읍면동 >= 11) 
  filter({
    census_data %>%
        .[, 1] %>%
        nchar() %>%
        `==`(2)} & 
    {census_data %>%
        .[, 1] %>%
        `>=`(11)}) 
census_data %>%
  names()
# names(census_data) 
# data_sido %>%
#   mutate(code = C행정구역별_읍면동)
data_sido$code <- data_sido$C행정구역별_읍면동 #> `map_id` 설정

code_chuncheon <- census_data %>%
  select(C행정구역별_읍면동) %>%
  filter({
    census_data %>%
      .[, 2] %>%
      `==`("춘천시")
  }) 
#  select(C행정구역별_읍면동) #> 앞에서 `select()`하고 `filter()`를 수행하거나 앞에서 `filter()` 를 수행하고 뒤에서 `select()`를 해도 결과는 같음.
#  .[, 1]  #> 값만 추출하고자 할 때는 이 방법이 적절함
code_chuncheon
# census_data$C행정구역별_읍면동[census_data$행정구역별_읍면동 == "춘천시"]
str(code_chuncheon)
code_chuncheon == "32010"  
code_chuncheon <- unname(unlist(code_chuncheon))
code_chuncheon
code_inje <- census_data %>%
  select(C행정구역별_읍면동) %>%
  filter({
    census_data %>%
      .[, 2] %>%
      `==`("인제군")
  }) 
code_inje <- unname(unlist(code_inje))
code_inje
data_sido %>%
  .[ , 1:6] %>%
  head(10)
data_sido %>%
  nrow()
data_sido %>%
  .[, 1:6]
```

## 시군구 데이터

```{r, sigungu}
data_sigungu <- census_data %>% #> 5자리 코드를 시군구로 걸러냄.
#   filter(nchar(C행정구역별_읍면동) == 5)
  filter(
    {census_data %>%
        .[, 1] %>%
        nchar() %>%
        `==`(5)})

data_sigungu %>%
  .[, 1:6]
data_sigungu %>%
  nrow()
# nrow(data_sigungu)
data_sigungu %>%
  .[1:10, 1:6]
data_sigungu %>% #> 시군구로 분류되어 있는 세종시 통계에 읍부, 면부, 동부 통계 포함
#   filter(substr(data_sigungu$C행정구역별_읍면동, 1, 2) == "29") %>%
#   .[ , 1:6] 
  filter({
    data_sigungu %>%
      .[, 1] %>%
      substr(1, 2) %>%
      `==`("29")}) %>%
  .[, 1:6]
# substr(data_sigungu[, 1], 3, 5) %in% c("003", "004", "005")
data_sigungu %>%
  .[, 1] %>%
  substr(3, 5) %>%
  `%in%`(c("003", "004", "005")) %>%
  `!`
data_sgg <- data_sigungu %>%
  filter({
    data_sigungu %>%
      .[, 1] %>%
      substr(3, 5) %>%
      `%in%`(c("003", "004", "005")) %>%
      `!` 
    })
#  filter(!(substr(data_sigungu[, 1], 3, 5) %in% c("003", "004", "005")))
# data_sgg %>%
#   mutate(code = C행정구역별_읍면동)
data_sgg$code <- data_sgg$C행정구역별_읍면동 #> `map_id` 설정
data_sgg %>%
  nrow()
# nrow(data_sgg)
data_sigungu %>%
  nrow()
# nrow(data_sigungu)
nrow(data_sigungu) - nrow(data_sgg)
data_sido %>%
  .[, 1:6]
data_sgg %>%
  .[, 1:6]

```

### 읍면동 데이터

```{r, emd}
data_emd <- census_data %>% #> 7자리 코드를 읍면동으로 걸러냄
  filter({
    census_data %>%
      .[, 1] %>%
      nchar() %>%
      `==`(7)
  })
#    filter(nchar(C행정구역별_읍면동) == 7)
# data_emd %>%
#   mutate(code = C행정구역별_읍면동)
data_emd$code <- data_emd$C행정구역별_읍면동 #> `map_id` 설정
data_emd %>%
  .[, 1:6] %>%
  head()
# head(data_emd[, 1:6])
data_emd %>%
  nrow()

data_chuncheon <- data_emd %>%
  filter({
    data_emd %>%
      .[, 1] %>%
      substr(1, 5) %>%
      `==`(code_chuncheon)    
  }) 
data_chuncheon %>%
  .[, 1:6]
data_inje <- data_emd %>%
  filter({
    data_emd %>%
      .[, 1] %>%
      substr(1, 5) %>%
      `==`(code_inje)    
  }) 
data_inje %>%
  .[, 1:6]
```

## 시도 인구 단계구분도 그리기

### `map_df`와 `data_sido`의 코드 불일치 문제 해결

```{r}
load("./korea_map.RData")
str(map_df$code)
table(map_df$code)
str(data_sido$code)
table(data_sido$code)
data_sido$code <- factor(data_sido$C행정구역별_읍면동)
levels(data_sido$code)
str(data_sido$code)
map_df$code_bak <- map_df$code
map_df$code <- factor(map_df$code, labels = levels(data_sido$code))
map_df$region <- map_df$code
str(map_df$code)
table(map_df$code)
str(map_df)
```

### `map@data` 와 인구 데이터 통합 방식 

(code 불일치 문제부터 해결해야 함)

```{r}
library(tmap)
shp1_demo <- shp_simp84
str(shp1_demo@data)
str(data_sido)
shp1_demo$code_bak <- shp1_demo$code
shp1_demo$code <- factor(shp1_demo$code, 
                         labels = levels(data_sido$code))
str(shp1_demo@data)
shp1_demo@data <- left_join(shp1_demo@data, data_sido, by = c("code" = "code"))
qtm(shp1_demo)
tm_shape(shp1_demo) +
tm_fill("총인구_명", thres.poly = 0) +
tm_facets("name_kor", free.coords = TRUE, drop.units = TRUE) +
tm_layout(legend.show = FALSE, 
          title.position = c("center", "center"), 
          title.size = 2, 
          fontfamily = "HCR Dotum LVT")
```

```{r, choroplethmap}
library(viridis)
library(RColorBrewer)
fill.pal <- colorRampPalette(brewer.pal(9, "YlGnBu"))(17)
ggplot(data = data_sido, 
       mapping = aes(map_id = code, 
                     fill = 총인구_명)) + 
  geom_map(map = map_df) +
  expand_limits(x = map_df$long, 
                y = map_df$lat) +
  theme(plot.title = element_text(family = "HCR Dotum LVT"),
        legend.title = element_text(family = "HCR Dotum LVT")) +
  ggtitle("시도 인구 단계구분도") + 
#  scale_fill_gradientn(name = "인구(명)", colours = c("white", "orange", "red")) +
  scale_fill_viridis(name = "인구(명)",
                     begin = 0.5, 
                     option = "C", 
                     direction = -1) +
#  scale_fill_distiller(name = "인구(명)", palette = "OrRd", trans = "reverse") +
  coord_map()
```

## Save

```{r, save}
saveRDS(census_data, "./census_data.RDS")
saveRDS(data_sido, "./data_sido.RDS")
saveRDS(data_sgg, "./data_sgg.RDS")
saveRDS(data_emd, "./data_emd.RDS")
```