```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## `VADeaths`

(@) 다음 `VADeaths`를 그 아래의 깔끔한(tidy) `VADeaths_tbl` 로 바꾸는 과정을 흐트러 놓았다.
순서대로 정리하시오. (사-다-나-가-라-마-바)

    ```{r VADeaths}
    VADeaths
    ```

    ```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse) # `tidyverse`를 검색 경로에 올려 놓음. 함께 불러들이는 패키지들과 경고문에 유의.
VADeaths_tbl <- VADeaths %>% # 최종 결과물을 `tibble` 형식으로 지정.
  as_tibble() %>% # 행렬 구조를 `tibble`구조로 변환. `tbl_df()`는 더 이상 사용되지 않음. 
  mutate(Age = row.names(VADeaths)) %>% # 행 이름으로 주어진 연령대를 글자벡터로 생성 
  gather(key = Place_Gender, # `Age`를 제외한 나머지 뱐수를 `key, value`쌍으로 정리하면서 새로운 변수명 부여.
         value = Rates, 
         -Age) %>%
  separate(Place_Gender, c("Place", "Gender"), # `Place_Gender`를 `Place`와 `Gender`로 분리.
           sep = " ") %>%
  mutate(Age = ordered(Age), # `Age`, `Place`, `Gender`를 순서형 범주와 명목형 범주로 변환
         Place = factor(Place), 
         Gender = factor(Gender,  # `Gender`에서 `level = `를 설정하지 않으면 알파벳 순에 따라 수준이 정해짐.
                         levels = c("Male", "Female"))) # 즉, `Female`이 1, `Male`이 2가 됨.
```

    ```{r}
    VADeaths_tbl 
    ```

(가) `mutate(Age = row.names(VADeaths)) %>%`  

(나) `as_tibble() %>%`  
  
(라) `gather(key = Place_Gender, value = Rates, -Age) %>%`

(마) `separate(Place_Gender, c("Place", "Gender"), sep = " ") %>%`

(바) `mutate(Age = ordered(Age), Place = factor(Place), Gender = factor(Gender,`  
               `levels = c("Male", "Female")))` 

(사) `library(tidyverse)` 

(@) 위의 `VADeaths_tbl`을 이용하여 다음 막대그래프들을 그릴 떼 [    ]를 채우시오.


```{r, echo = FALSE, eval = TRUE}
ggplot(data = VADeaths_tbl,
              mapping = aes(x = Age, 
                            y = Rates, 
                            fill = Age)) +
geom_bar(stat = "identity", 
         position = position_dodge()) + 
scale_fill_grey(guide = FALSE) +
facet_grid(Gender ~ Place)
```

```
ggplot(data = VADeaths_tbl,
              mapping = aes(x = [Age], 
                            y = [Rates], 
                            fill = [Age]) +
geom_bar(stat = "[identity]", 
         position = position_[dodge]()) + 
scale_fill_grey([guide] = FALSE) +
facet_grid([Gender] ~ [Place])
```

<P style="page-break-before: always">